# .github/workflows/bandit.yml
name: Bandit Security Scan

on:
  push:
    branches:
      - 'feature/**'  # Triggers on any branch starting with 'feature/'
      - 'feat/**'
      - 'main'
  workflow_dispatch:

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      run: |
        bandit -r . -ii -o bandit_report.json -f json || true
      # bandit -r . -ll -ii -o bandit_report.html -f html || exit 1


    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit_report.json
